// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PulseCheck.MainApp.Models
{
    public partial class Configuration
    {
        public Configuration()
        {
            Components = new HashSet<Component>();
        }

        public int Id { get; set; }
        public string Uri { get; set; }
        public string Name { get; set; }
        public string DiscoveryService { get; set; }

        public virtual ICollection<Component> Components { get; set; }
    }
}