// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PulseCheck.MainApp.Models
{
    public partial class Failure
    {
        public int Id { get; set; }
        public string HealthCheckName { get; set; }
        public DateTime LastNotified { get; set; }
        public bool IsUpAndRunning { get; set; }
    }
}