// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RSWMonitor.MainApp.Models
{
    public partial class UserAction
    {
        public int UserActionId { get; set; }
        public string UserActionName { get; set; }
    }
}