// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RSWMonitor.RemoteMonitor.Models
{
    public partial class HealthCheckExecutionEntry
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public TimeSpan Duration { get; set; }
        public int? HealthCheckExecutionId { get; set; }
        public string Tags { get; set; }

        public virtual Execution HealthCheckExecution { get; set; }
    }
}